### ISSUE TITLE
Unable to open some pokemon sprites

### ISSUE THREAD

**Issue by quentinmarolleau** [acxz/pokeshell#11]
I report a bug during the attempt of displaying some specific pokemon sprite.
Here is an example of the error message returned in the terminal:

```
parse error: Invalid numeric literal at line 1, column 4
not-shiny:milcery+female
not-shiny:tropius+male
convert: unable to open image 'deerling+male-big.png': Aucun fichier ou dossier de ce type @ error/blob.c/OpenBlob/3570.
convert: no images defined `/home/quentin/.cache/pokeshell/not-shiny:deerling+male-big.png' @ error/convert.c/ConvertImageCommand/3342.
convert: unable to open image 'deerling+male-big.png': Aucun fichier ou dossier de ce type @ error/blob.c/OpenBlob/3570.
```
Here is a non exhaustive list of pokemons causing a bug. I only found those by chance, the complete list is probably much larger:
`deerling`
`basculin`
`scatterbug`
`flabebe`
`giratina`

Here is the config I use:

![image](https://user-images.githubusercontent.com/30953121/201232387-235e87c3-725b-4de3-87dd-69256645d50e.png)

**Comment by acxz** [comment]
I believe this is a duplicated of #7 
Can you confirm and if so add your comment under that issue and close this one.

**Comment by quentinmarolleau** [comment]
That is perhaps the case. Indeed animated sprites do not work properly.
But I am also facing problems with non-animated ones.
