### ISSUE TITLE
Los Sprites están muy pixelados y no reconoce los sprites

### ISSUE THREAD

**Issue by Keytaro2** [acxz/pokeshell#21]
https://github.com/user-attachments/assets/0f41ae2e-7037-4cc6-a3b3-d3fa8c834288

Uploading new.mp4…

En termux android

**Comment by Keytaro2** [comment]
Uploading new.mp4…

**Comment by Keytaro2** [comment]
Uploading new.mp4…

**Comment by acxz** [comment]
duplicate of #13 

just want to point out that it is pretty cool you have it working on android!
