### ISSUE TITLE
Image sprites appear distorted/glitched

### ISSUE THREAD

**Issue by laoraryn** [acxz/pokeshell#23]
Hi, I just found this and I love it! However when I try and use it, the sprites come out distorted, most similar to the Mantine in #6. 

I use Black Box, but it's also happening in my default terminal. Here's some example images, both with neowofetch (running `pokeshell random`) and just `pokeshell random` on its own:

Default Linux Mint terminal:
![image](https://github.com/user-attachments/assets/dc9cbcc6-31a6-4694-ad58-a0f923fd1e55)

![image](https://github.com/user-attachments/assets/c6540b13-7c8e-4f4a-9d3a-747732abfc01)

Black Box:
![image](https://github.com/user-attachments/assets/f748292d-e89a-4ef8-bf5c-ceacdf739b51)

![image](https://github.com/user-attachments/assets/82d6bbb7-90e5-4aa7-bb60-e22236097e41)

Dependency versions:
![image](https://github.com/user-attachments/assets/bd45019d-0dca-4ea8-9c13-7d57ae917e98)

Any ideas on what might be causing it? :/ Thanks!

**Comment by acxz** [comment]
Hello @laoraryn glad you love it! I'm slowing trying to get back to fixes the issues in this project. So I apologize, if I don't get to this quickly.

I'll try to help and also point you to the relevant line, so you can can better debug and tweak the display.

First off, all of the display is handled by `chafa`. For the "big" sprites, which is the default for the `pokeshell` command, the following `chafa` command is executed: 
https://github.com/acxz/pokeshell/blob/8dd4d604fb8c689a743cb17508dd48800b2ce813/bin/imageshell/imageshell.sh#L65

Now this line should provide pixel perfect display, but it isn't doing that. Most likely because the image is being resized.

Notice the `--symbols all` option being passed in, this is something you can change if you want. But let me first try to reproduce.

**Comment by acxz** [comment]
![image](https://github.com/user-attachments/assets/7096a401-7bc4-425f-a437-26d73d2a0b8e)

Looks like `hyfetch` added some spacing since I last used it, in their `ascii` image mode. Doesn't look as nice as it used (i.e. the politoed example in the readme). This might be cause for an upstream issue. I double checked the image generated and not issues there.

**Comment by laoraryn** [comment]
Unfortunately I'm still getting the same glitched images :(

![image](https://github.com/user-attachments/assets/cd3c91dd-d962-4b4e-8e1e-a39d61a2ed1d)

Just because I'm not 100% sure I know what you recommended, here's what I did:

1. sudo ./uninstall.sh in my old pokeshell folder
2. Download the new .zip file from this repo
3. sudo ./install.sh in that new folder
4. Restart terminal

Did I need to do anything with hyfetch/Magick/chafa? I'm relatively new to messing with the terminal so I'm not sure how to do what you described.

**Comment by laoraryn** [comment]
Also, no worries at all on potential slow replies! I appreciate the help :)

**Comment by acxz** [comment]
Ah thanks for reporting back, I'd first make sure that you are removing the cache `pokeshell -r`. (I might make this a part of the uninstall script to be honest)
But if you are using `pokeshell random`, then those images wouldn't have been cached anyway...

![image](https://github.com/user-attachments/assets/d47b8410-45b8-471f-8df5-c0db66fe8915)

This might be something to investigate. What's your imagemagick version? It could be an older version of magick that doesn't support how I'm currently using imagemagick. I don't remember the command to check the version off the cuff. Maybe something like `magick --version`? You might have to search the web to make sure that is correct.

**Comment by Cloudismss** [comment]
I'm having the same issue as above. Clearing the cache with `pokeshell -r` hasn't changed the results .

![image](https://github.com/user-attachments/assets/ea1af1a8-c046-4587-9437-fd2f21c38edf)

My ImageMagick version is 7.1.1-39 if that is helpful!

**Comment by laoraryn** [comment]
I'm also using 7.1.1-39! Clearing the cache didn't help. But also, the random Pokemon ARE being cached for me - after running `pokeshell -r`, I ran random 3 times: 
![image](https://github.com/user-attachments/assets/a2f4d807-c26a-4e0c-a2bb-8f0620574177)

(I also installed the Starship prompt with my other "oooh shiny new OS" tinkering, which is why it looks different, but that doesn't seem to have made a difference)

**Comment by Cloudismss** [comment]
I ran uninstall.sh, cloned and ran install.sh, but I'm unfortunately still getting the same distorted result. Can confirm the magick deprecated command error is gone tho! My `chafa` is version 1.14.2

**Comment by acxz** [comment]
can you post an image of your output?

**Comment by Cloudismss** [comment]
Yes, this is the entire output from `pokeshell -a piplup` (this image was not cached beforehand)

![image](https://github.com/user-attachments/assets/cbc66899-6624-4c84-9e8b-9b39577c3d8e)

**Comment by Cloudismss** [comment]
Maybe this will be helpful - the `-b` flag seems to be no different from the call without `-b` flag

![image](https://github.com/user-attachments/assets/ca7b77ef-fb0d-40d0-959e-56d22b4d244d)

**Comment by laoraryn** [comment]
unfortunately I'm still getting the PNG error. I'm not sure if I screwed something up - I had to reinstall Magick and Chafa also, so I'm not sure if I could've knocked something loose while doing that. They're still the same versions as they were before

Here's the output for me as of all the fresh installs. It looks slightly better than before, but still distorted:
![image](https://github.com/user-attachments/assets/12b76f46-e892-41e3-a008-676e97683a34)

**Comment by acxz** [comment]
> Maybe this will be helpful - the `-b` flag seems to be no different from the call without `-b` flag

@Cloudismss please read `pokeshell -h`, `-b/--big` is the default behavior.

**Comment by acxz** [comment]
> Yes, this is the entire output from `pokeshell -a piplup` (this image was not cached beforehand)

For the animations, see #13. This issue is for images only.

**Comment by acxz** [comment]
> unfortunately I'm still getting the PNG error. I'm not sure if I screwed something up - I had to reinstall Magick and Chafa also, so I'm not sure if I could've knocked something loose while doing that. They're still the same versions as they were before

The reinstallation shouldn't be an issue at all. But what is an issue is the fact you still have that warning. Let's work on getting rid of that.

Can you first try to open up the `bin/imageshell/imageshell.sh` in a text editor and search for `PNG`? Let me know if that search is successful. If the search passes then you have an outdated `pokeshell` codebase and you'll have to redownload. If the search fails, then we may have to see what we can do about the delegates your `magick` install supports (as seen from your `magick --version` output).

**Comment by acxz** [comment]
Note if you want pixel perfect images (useful for the `-s` small and `-b` big sprites), install `timg`. See: https://github.com/hpjansson/chafa/discussions/70 if you want to dig deeper.

**Comment by acxz** [comment]
@laoraryn any updates? I'll go ahead and close this issue due to lack of activity, but please feel free to comment on this issue with responses to my above comments.

**Comment by laoraryn** [comment]
Hi @acxz, I'm so sorry for the delay here!! My computer did its best to brick itself so I've done a complete reinstall of almost everything, and just got back around to getting Pokeshell reinstalled. 

I installed timg as you suggested and the images do look significantly better! However I'm still getting the weird png error, if you have the time to help me figure it out I'd really appreciate it :)

Here's my versions, and my current neowofetch:

- GNU bash, version 5.2.21(1)-release (x86_64-pc-linux-gnu)
- curl 8.5.0 (x86_64-pc-linux-gnu)
- ImageMagick 7.1.1-41 Q16-HDRI x86_64 d7d490223:20241115 
- timg 1.5.2+ (Debian package 1.5.2-1build2) 

![image](https://github.com/user-attachments/assets/6ddb41c9-7a6c-4fa1-92c6-f48f94e3efd0)

For your question about the `imageshell.sh` file, I'm not sure whether you're saying I'm supposed to have png in the file or not? It has 4 hits, 3 of which are in comments. 2 comments + 1 line of code are clustered together here:

![image](https://github.com/user-attachments/assets/4c3dcc58-792c-48f1-83ba-1009f9cb64a4)

I'm not sure how I could have an outdated version of the code? I `git clone`'d it literally a couple hours ago completely fresh, but if I do, please let me know how to get the proper version.

Thank you so much, and sorry again for disappearing!!

**Comment by laoraryn** [comment]
probably-important info: trying to add `-s` or `--small` (or the big equivalents) fails with this error, which seems to reference that line 63: 
![image](https://github.com/user-attachments/assets/d7cc8b1c-ce01-4115-827b-be0b77411683)
