### ISSUE TITLE
Support for Chafa <= 1.2.1

### ISSUE THREAD

**Issue by EthanNicotine** [acxz/pokeshell#5]
I'm using Ubuntu and I've been using Linux for a little over a week so if the problem is with the distribution I apologize in advance.

Every time I run the installer I get the following message
![imagen](https://user-images.githubusercontent.com/64540732/184614600-b3e00524-04e9-41e9-b289-0bdadc0503a2.png)

```
cp: cannot stat 'pokeshell': No such file or directory
cp: cannot stat 'pokeshell-completion.bash': No such file or directory
```

**Comment by acxz** [comment]
> been using Linux for a little over a week

Welcome to linux!

One quick thing, its better to submit errors as text and codeblocks instead of images. This is so that, others can search through the issues or on Github and are able to find similar error messages. They won't be able to search text through images.

You can use codeblocks by wrapping your message with triple backticks (```). For a code line you can just use a single backtick.

> Every time I run the installer I get the following message

thanks for reporting this! I recently changed the directory structure, but I seem to have forgot to propagate the changes into the install/uninstall script.

**Comment by EthanNicotine** [comment]
> > been using Linux for a little over a week
> 
> Welcome to linux!
> 
> One quick thing, its better to submit errors as text and codeblocks instead of images. This is so that, others can search through the issues or on Github and are able to find similar error messages. They won't be able to search text through images.
> 
> You can use codeblocks by wrapping your message with triple backticks (```). For a code line you can just use a single backtick.
> 
> > Every time I run the installer I get the following message
> 
> thanks for reporting this! I recently changed the directory structure, but I seem to have forgot to propagate the changes into the install/uninstall script.

Thanks for the welcome and for this fun application, I have edited my report in case someone downloaded this version and encountered the same error he can get here as you told me :+1:

**Comment by acxz** [comment]
Thanks for that!

And in the meantime, I also fixed the error with the following commit: [9ed5a6c](https://github.com/acxz/pokeshell/commit/9ed5a6c2e70f538f297a8730d7ccb87a4fa2dd28)

If you could test out the latest master branch, I would appreciate it! If it works, then you can go ahead and close the issue yourself.

Feel free to open more issues as they pop up.

**Comment by EthanNicotine** [comment]
The installation is already working great, all directories are copied to their place.

However when using the command it doesn't work well, maybe I have installed the dependencies wrong, now I was on my study break, this afternoon, when I finish, I will check if they are well installed.


```
sudo apt-get install jq
```
And receive:

```
/usr/local/bin/pokeshell: line 458: convert: command not found
/usr/local/bin/pokeshell: line 462: convert: command not found
chafa: Unknown option --scale
```

**Comment by acxz** [comment]
Can you post the output of `chafa --version`? Most likely you might be using an older version of chafa.

**Comment by EthanNicotine** [comment]
Chafa version 1.2.1

It is definitely an old version, apparently in the ubuntu repository it is not updated, I will have to compile it myself from their github.

Thank you very much for the help!

**Comment by acxz** [comment]
Looks like `chafa` added support for the `--scale` option from version `1.12.0` https://github.com/hpjansson/chafa/commit/17aa6a4cdb1586c7026d9597fae900c543109b92

And here are the versions of `chafa` across many different distributions: https://repology.org/project/chafa/versions

I'm guessing you are using ubuntu 20.04?

I should try to support older distributions however, I'll try to see if I can use an older version of chafa in pokeshell so users don't have to compile it.

**Comment by acxz** [comment]
@EthanNicotine can you test the latest version now?
I have removed the use of the `--scale` flag in d8093cc

**Comment by EthanNicotine** [comment]
Yes, everything is working great, how nice :)

Before installing the last update I uninstalled it (I don't know if this was necessary but just in case) and I found this error, in case it's something you would like to correct, anyway the uninstall and new installation worked fine for me


```
sudo ./uninstall.sh 
```
```
removed '/usr/local/bin/pokeshell'
removed '/usr/local/share/bash-completion/completions/pokeshell'
rm: cannot remove '/usr/local/share/zsh/site-functions/_pokeshell': No such file or directory
rmdir: removing directory, '/usr/local/bin'
rmdir: failed to remove '/usr/local/bin': Directory not empty
rmdir: removing directory, '/usr/local/share/bash-completion/completions'
rmdir: removing directory, '/usr/local/share/bash-completion'
rmdir: removing directory, '/usr/local/share/zsh/site-functions'
rmdir: failed to remove '/usr/local/share/zsh/site-functions': No such file or directory
rmdir: removing directory, '/usr/local/share/zsh'
rmdir: failed to remove '/usr/local/share/zsh': No such file or directory

```

**Comment by acxz** [comment]
> I found this error

Done

> --format

kk I'll see if I can remove this function to make pokeshell compat with the chafa version that is available in your ubuntu version.

> I know it's not your project, but if you don't mind I'll ask you, to install the latest version of chafa following the build instructions I must first uninstall the version I currently have?

You don't have to. by default the install of chafa from `apt` will install under the `/usr/` directory. You can see the list of files installed with the chafa package with the `dpkg-query -L chafa` command.

When you install manually, you should install to `/usr/local` so you can have two copies that don't conflict with each other. By default the priority will be for the files in `/usr/local` over `/usr/`. It could vary so the best way to make sure you are using the version of chafa you think you are using is to run the `which` command like so: `which chafa` and that will give the absolute path or location of the chafa executable that is running.

**Comment by acxz** [comment]
@EthanNicotine can you test the codebase again with the default version of chafa?

This commit introduced the `--format` flag: https://github.com/hpjansson/chafa/commit/a186278342fc3ec1b1d7ab81aff1e73a8ca056eb and I believe I have added a workaround to fallback to a command without using the `--format` flag.

**Comment by EthanNicotine** [comment]
The animations do not work when for example I put

 "pokeshell -a lugia" 

I get the following message

"chafa: Unknown option --format".

Anyway I managed to install the latest version of chafa (I uninstalled it to test your update).

I have only had to put "chafa" in my path: "/usr/local/bin/"
I downloaded it from here (Stand-alone executable): https://hpjansson.org/chafa/download/

**Comment by acxz** [comment]
> I downloaded it from here (Stand-alone executable):

Nice! Looks like you didn't have to compile after all.

I'd like to keep this issue open for a bit longer though, since I would like to make the codebase compatible with an older Ubuntu version since it is a popular distribution.

**Comment by EthanNicotine** [comment]
I don't know if it's just me but in this latest version there are no more transparencies but a black background!

![imagen](https://user-images.githubusercontent.com/64540732/184861902-5af62fc2-4900-490f-84e0-dfdfc93faad2.png)

**Comment by acxz** [comment]
hmm interesting i have version 1.12.1 and I don't observe this behavior.

This could be a bug with the staticly linked executable that you downloaded, I'd post an issue about this over at the chafa github repo: https://github.com/hpjansson/chafa if you still want to use the latest version.

Or... you could help me test out the `--format` issue with the older chafa version. :wink: :wink:

**Comment by acxz** [comment]
Actually one thing you can do the just confirm its not a chafa issue. Can you open up the direction in `~/.cache/pokeshell` and view the image files in there? Do those also have a black background?

**Comment by EthanNicotine** [comment]
> hmm interesting i have version 1.12.1 and I don't observe this behavior.
> 
> This could be a bug with the staticly linked executable that you downloaded, I'd post an issue about this over at the chafa github repo: https://github.com/hpjansson/chafa if you still want to use the latest version.
> 
> Or... you could help me test out the `--format` issue with the older chafa version. wink wink

Transparency seems to work when I type sudo su before use pokeshell.

I'll help you with that later, I have to go now :P!

**Comment by acxz** [comment]
> Transparency seems to work when I type sudo su before use pokeshell.

Weird...

> I'll help you with that later, I have to go now :P!

Have a good day! or afternoon or night!

**Comment by EthanNicotine** [comment]
> Or... you could help me test out the `--format` issue with the older chafa version. wink wink

With the old version of chafa it loads the image but with the animation command nothing happens:

https://user-images.githubusercontent.com/64540732/184937442-9fb2e873-7693-4876-91e1-2f33ca6c92ab.mp4

Regarding the black background, for some reason when I update the version of ```chafa``` in the way I mentioned before "copy chafa to ```/usr/local/bin```", the background appears black until I apply ```sudo su```

https://user-images.githubusercontent.com/64540732/184938458-d4e68982-88f9-45d4-8370-41ee42e58c2e.mp4

**Comment by acxz** [comment]
> With the old version of chafa it loads the image but with the animation command nothing happens:

Can you post the output of `chafa --format symbols --symbols all ~/.cache/pokeshell/not-shiny:lugia+male-big.png`? Make sure you also include the next shell prompt. It should have some error number. Like this:
```
acxz@archard ~/vcs/git/github/acxz/pokeshell (git)-[master] % chafa --formats symbols --symbols all ~/.cache/pokeshell/not-shiny:lugia+male-big.png
chafa: Unknown option --formats
2 acxz@archard ~/vcs/git/github/acxz/pokeshell (git)-[master] %
```

**Comment by EthanNicotine** [comment]
> 

I only get this

```
root@riceOS:/home/ethan# chafa --format symbols --symbols all ~/.cache/pokeshell/not-shiny:lugia+male-big.png
chafa: Unknown option --format
root@riceOS:/home/ethan# 
```

**Comment by EthanNicotine** [comment]
> I think you need to run without being the superuser. Can you try that and report back? If your default `chafa` points to your manually downloaded one, you can run `/usr/bin/chafa <rest of command>` instead to forcefully run the `chafa` installed from apt.

Same result:

```
/usr/bin/chafa: Unknown option --format
```

**Comment by acxz** [comment]
Can you post the full output including the prompt and the command you used as well as the prompt that shows up right after.

**Comment by EthanNicotine** [comment]
I don't understand very well how to do what you are telling me, I have taken these pictures (left zsh, right bash)

![imagen](https://user-images.githubusercontent.com/64540732/185341535-25be707e-5ebf-4fc7-9412-e63b08a749c4.png)

If this is not what you were asking for please guide me a little more and this newbie will help you as much as he can :)

**Comment by acxz** [comment]
Thanks that was helpful. I was interested in the output of your first terminal. The key thing im looking for here is an error code that `chafa` should spit out when you use an option that it doesn't recognize, such as `--format` for older `chafa` versions. Also note, you only use `/usr/bin/chafa` or `chafa` not both. And `usr/bin/chafa` is not a file, `/usr/bin/chafa` with the forward slash in front is the file, causing the error on the second terminal.

Let's try one more thing and if it doesn't work then I'm not sure how to proceed.

Can you show the full output (including the command you have typed in and the shell prompt that appears after you run the command) for the following command?

```
/usr/bin/chafa --format ~/.cache/pokeshell/not-shiny:lugia+male-big.gif || /usr/bin/chafa ~/.cache/pokeshell/not-shiny:lugia+male-big.gif
```

**Comment by jejomar** [comment]
Hi! I also just encountered the problem where I get a black background for static images.

I fixed the problem by adding the `--format symbols` to line `480` and `482` of the `pokeshell` file inside the `bin` folder.

Hope this helps.

**Comment by acxz** [comment]
Closing this issue as chafa is on 1.14 on even the slower moving distros and the content of this issue is quite outdated.
