### ISSUE TITLE
Broken characters in alacritty, hyper

### ISSUE THREAD

**Issue by guyjin** [acxz/pokeshell#8]
I can run pokeshell just fine, but I'm seeing broken characters in the sprite that gets rendered:
![image](https://user-images.githubusercontent.com/109336/185940453-9dc60d46-59c0-4ffa-b665-91aa94b81b77.png)
and
![image](https://user-images.githubusercontent.com/109336/185940652-b6f844f4-9c74-4906-8a2b-3430af7c8346.png)

I switched back to bash from zsh.  I see this in iTerm2 and Terminal.  I *think* it's a font issue, but I can't find font (powerline or otherwise) that fixes this.  Everything I know to check is set to UTF-8 already.

Running this in iTerm2 v3.4.16 on MacOS Monterey v.12.5.1

Thank you for maintaining this!

**Comment by acxz** [comment]
Can you run and show the output of `chafa ~/.cache/pokeshell/not-shiny:nidoran-f+male`?

Ye it is most likely a font issue. What font are you currently using?

**Comment by guyjin** [comment]
Chafa is strangely throwing an error even though the files are there in ~/.cache/pokeshell and appear to be readable.
![image](https://user-images.githubusercontent.com/109336/185948947-aeae4f9b-87a5-4443-b83e-beece6f1c9f1.png)
Currently, I'm using MesloLGS NF as I use the powerline10k theme in ZSH.  I've switched to bash try to get this working and have tried several other fonts as well, (Courier, Monaco, etc.)  Is there.
![image](https://user-images.githubusercontent.com/109336/185950402-1ac9944d-9425-459b-a545-08804c9aa9c8.png)

**Comment by acxz** [comment]
> Chafa is strangely throwing an error even though the files are there in ~/.cache/pokeshell and appear to be readable.

mb, i forgot to type in the `.png` at the end.

**Comment by guyjin** [comment]
No problem!  I don't see that file in there, but there's  -big version: 
![image](https://user-images.githubusercontent.com/109336/185954273-a50dabc1-7376-4edb-8dc8-a6742e71af75.png)

Yes, I'll try that font!

**Comment by acxz** [comment]
Okay now try `chafa --symbols all ~/.cache/pokeshell/not-shiny:nidoran-f+male-big.png` with your current font.

**Comment by guyjin** [comment]
Here's the result using my font.
![Screen Shot 2022-08-22 at 9 09 10 AM](https://user-images.githubusercontent.com/109336/185955456-4d8a4d16-0760-47e7-b774-aec53ad98882.png)

Here's the result with Juliamono
![image](https://user-images.githubusercontent.com/109336/185955580-d32ee660-6799-413b-91cf-cefa4710ec5d.png)

Just running `pokeshell random` with Juliamono active
![image](https://user-images.githubusercontent.com/109336/185955780-f6ed5b0e-ec40-46b6-95a3-0281b50d88b6.png)

**Comment by acxz** [comment]
Okay so based on the nidoran, it does seem like using JuliaMono helped, but its still not all the way there yet.

Do you have another terminal you could try? Certain terminals may render/not render certain characters, whether the font supports it or not.

**Comment by guyjin** [comment]
Here's a shot in Alacritty with Juliamono set.
![image](https://user-images.githubusercontent.com/109336/185961183-b9bfb18b-4c21-4a9e-b8af-6a094c20b61d.png)

**Comment by acxz** [comment]
Can you use the same nidoran image? When testing it is important to keep the same inputs until we nail the issue down.

**Comment by acxz** [comment]
Also I do most of my testing on termite and kitty. So just ensure we have the same term emu, can you test on the kitty terminal as well.

Let's run the following command to be more explicit: `chafa --format symbols --symbols all ~/.cache/pokeshell/not-shiny:nidoran-f+male-big.png`

**Comment by guyjin** [comment]
Understood.  Here it is in Kitty:
![image](https://user-images.githubusercontent.com/109336/185967010-21d37ae1-026b-4306-804b-2c585be8c036.png)

Looks like it works much better in Kitty!

**Comment by acxz** [comment]
Yeah, it seems that alacritty, iTerm2, and Hyper don't have good unicode support.

I'd recommend using kitty on mac os, or making issues/sending PRs to those above terminals that don't have proper unicode support.

Feel free to close this issue if you think it is resolved.
